### ISSUE TITLE
Can you  Uplaod the Dataset , if available ?

### ISSUE THREAD

**Issue by gopisadi3** [Janhavikc/Sentiment-Analysis-using-Naive-Bayes-#1]
Can you please provide with the dataset which you have used for this project. It would be helpful :-)

**Comment by gopisadi3** [comment]
> Can you please provide with the dataset which you have used for this project. It would be helpful :-)

Dataset??

**Comment by Janhavikc** [comment]
Dataset was collected from an online health forum. Due to privacy policy, I can't share the dataset with you. You may search such health forum online available accordingly, make csv file and can label class as exist, deteriorate and recover.
